package com.lenhujori.stablediffusion

data class RequestBody(
    val prompt: String,
    val negative_prompt: String,
    val styles: List<String>,
    val seed: Int,
    val subseed: Int,
    val subseed_strength: Float,
    val seed_resize_from_h: Int,
    val seed_resize_from_w: Int,
    val sampler_name: String,
    val scheduler: String,
    val batch_size: Int,
    val n_iter: Int,
    val steps: Int,
    val cfg_scale: Float,
    val width: Int,
    val height: Int,
    val restore_faces: Boolean,
    val tiling: Boolean,
    val do_not_save_samples: Boolean,
    val do_not_save_grid: Boolean,
    val eta: Float,
    val denoising_strength: Float,
    val s_min_uncond: Float,
    val s_churn: Float,
    val s_tmax: Float,
    val s_tmin: Float,
    val s_noise: Float,
    val override_settings: Map<String, Any>,
    val override_settings_restore_afterwards: Boolean,
    val refiner_checkpoint: String,
    val refiner_switch_at: Float,
    val disable_extra_networks: Boolean,
    val firstpass_image: String,
    val comments: Map<String, String>,
    val enable_hr: Boolean,
    val firstphase_width: Int,
    val firstphase_height: Int,
    val hr_scale: Float,
    val hr_upscaler: String,
    val hr_second_pass_steps: Int,
    val hr_resize_x: Int,
    val hr_resize_y: Int,
    val hr_checkpoint_name: String,
    val hr_sampler_name: String,
    val hr_scheduler: String,
    val hr_prompt: String,
    val hr_negative_prompt: String,
    val force_task_id: String,
    val sampler_index: String,
    val script_name: String,
    val script_args: List<String>,
    val send_images: Boolean,
    val save_images: Boolean,
    val alwayson_scripts: Map<String, Any>,
    val infotext: String
)
